### ISSUE TITLE
Long password throws an error

### ISSUE THREAD

**Issue by mjhm** [dropbox/zxcvbn#194]
zxcvbn = require('zxcvbn')
```
zxcvbn(require('crypto').randomBytes(200).toString('hex'))

===>

TypeError: Cannot read property 'i' of undefined
    at /Users/johnmclaughlin/git/rms/rms-one-iam/node_modules/zxcvbn/lib/scoring.js:208:16
    at Object.most_guessable_match_sequence (/Users/johnmclaughlin/git/rms/rms-one-iam/node_modules/zxcvbn/lib/scoring.js:229:30)
    at zxcvbn (/Users/johnmclaughlin/git/rms/rms-one-iam/node_modules/zxcvbn/lib/main.js:31:20)
    at repl:1:1
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:340:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

Related: https://github.com/dropbox/zxcvbn/issues/69

**Comment by lowe** [comment]
Hi @mjhm, this is discussed briefly in the [perf section](https://github.com/dropbox/zxcvbn#performance) of the README. To avoid unexpected behavior, we currently recommend truncating user input before passing to `zxcvbn()`. But if others feel strongly, I'd be open to considering truncation.

**Comment by KunalTanwar** [comment]
[zxcvbn-ts](https://github.com/KunalTanwar/zxcvbn-ts) doesn't crash on long passwords — input is capped at 128 characters before any processing, so the DP never receives a string long enough to trigger the undefined access. Passwords of any length are handled safely.
