### ISSUE TITLE
Cannot find module './zxcvbn/zxcvbn' (coffee script problem)

### ISSUE THREAD

**Issue by dominictarr** [dropbox/zxcvbn#77]
This module needs to ship with prebuilt javascript code, otherwise it doesn't work without coffeescript.
the simplest way to do this would be to call a build step from within a prepublish script in the package.json.

here is the error I get
``` js
$ npm install zxcvbn
$ node
> require('zxcvbn')
Error: Cannot find module './zxcvbn/zxcvbn'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dominic/c/experiments/node_modules/zxcvbn/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)


```

**Comment by binarykitchen** [comment]
agree with that and not minified please - in my case i need it to debug other zxcvbn related bugs ...

**Comment by binarykitchen** [comment]
@dominictarr you can use my npm-published fork until it's fixed https://www.npmjs.com/package/zxcvbn-npm

**Comment by lowe** [comment]
npm fix coming soon -- I'm working w the original publisher to get access
to the registry.

**Comment by lowe** [comment]
I fixed the npm package and updated the README -- this should just work now. 

@binarykitchen for debugging I would recommend the setup described in the README vs directly including the zxcvbn.js bundle (whether minified or not).

**Comment by binarykitchen** [comment]
Your updates are good, thanks. But there are still things you need to change. Will write new tickets.
